server:
    port: 8888

spring:
    profiles:
        active: docker
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/appkr/spmia-study
                    searchPaths: configsvr/src/main/resources/config/license-service,configsvr/src/main/resources/config/organization-service
