server:
    port: 8761

spring:
    output:
        ansi:
            enabled: ALWAYS

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 5
    serviceUrl:
        defaultZone: http://localhost:8761