# @see configsvr/src/main/resources/config/${spring.application.name}/${spring.application.name}.yml
server:
    port: 8090

spring:
    output:
        ansi:
            enabled: ALWAYS
    cloud:
        config:
            enabled: true
            uri: http://localhost:8888
    jpa:
        hibernate:
            ddl-auto: none
    datasource:
        initialization-mode: always

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
