# @see configsvr/src/main/resources/config/${spring.application.name}/${spring.application.name}.yml
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8090
